version: '3'

services:
  frontend:
    image: appletreecy/dockerchatgptclient:1.1
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    container_name: chatgpt_frontend1
    #command: npm run dev


  backend:
    image: appletreecy/dockerchatgptserver:1.1
    working_dir: /usr/src/app
    ports:
      - "5001:5001"
    container_name: chatgpt_backend1


